// One-off script: extract problem_id -> ISO scheduled date from app/page.tsx
// into app/lib/schedule.ts. Re-run if the dataset in page.tsx changes.
import fs from 'node:fs';
import path from 'node:path';

const SRC = path.join(process.cwd(), 'app', 'page.tsx');
const OUT = path.join(process.cwd(), 'app', 'lib', 'schedule.ts');

const MONTH_IDX: Record<string, number> = { Apr: 3, May: 4, Jun: 5, Jul: 6 };

const src = fs.readFileSync(SRC, 'utf8');
const re = /id\s*:\s*"([^"]+)"[^}]*?day\s*:\s*"([^"]+)"/g;

const entries: Array<[string, string]> = [];
let m: RegExpExecArray | null;
while ((m = re.exec(src))) {
  const id = m[1];
  const dayKey = m[2];
  const km = dayKey.match(/\w+,\s+(\w+)\s+(\d+)/);
  if (!km) continue;
  const mon = km[1];
  const dayNum = Number(km[2]);
  if (!(mon in MONTH_IDX)) continue;
  const monthNum = MONTH_IDX[mon] + 1;
  const iso = `2026-${String(monthNum).padStart(2, '0')}-${String(dayNum).padStart(2, '0')}`;
  entries.push([id, iso]);
}

const body =
  `// AUTO-GENERATED by scripts/build-schedule.ts. Do not edit by hand.\n` +
  `// Maps each problem_id to its scheduled study date (ISO YYYY-MM-DD).\n\n` +
  `export const PROBLEM_SCHEDULE: Record<string, string> = {\n` +
  entries.map(([id, iso]) => `  "${id}": "${iso}",`).join('\n') +
  `\n};\n\n` +
  `export const TOTAL_PROBLEMS = ${entries.length};\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body, 'utf8');

console.log(`Wrote ${OUT} with ${entries.length} entries`);
